#!/bin/bash

set -e 
$PREPARE_DEFAULT > /dev/null
$INCLUDE_FUNCS
cd $WC

if [[ $UID -eq 0 ]]
then
	mv device device-2
	mkdir device
	mv device-2 device/device-node

	chown 1.1 empty-file

	# We don't know whether there's sudo, su or something else possible.
	# lchown() isn't available on the cli, so use perl.
	mkdir -m 777 all_open
	perl -e '$(=$)="5 5"; $<=$>=1; symlink(shift(), shift()) || die $!' device all_open/KK

	rm reclink
	touch reclink

	echo "     ci"
	$BINq ci -m "changed dev to dir/dev and link to file"
	echo "     st1"
	$BINq st

	$WC2_UP_ST_COMPARE
else
  $WARN "cannot test device creation as normal user."
fi

