#!/bin/bash

set -e 
$PREPARE_DEFAULT > /dev/null
$INCLUDE_FUNCS
cd $WC

mv tree/a tree/Aa
mv tree/b tree_b

echo "     ci"
$BINq ci -m "renamed two directories"
echo "     st1"
$BINq st

$WC2_UP_ST_COMPARE
