#!/bin/bash

set -e 
$PREPARE_CLEAN > /dev/null
$INCLUDE_FUNCS
cd $WC

COUNT1=20
COUNT2=20
COUNT3=20
seq1=`seq 1 $COUNT1`
seq2=`seq 1 $COUNT2`
seq3=`seq 1 $COUNT3`

# We have to escape ( ) and *, as the shell would try to interpret these.
exp_count=`expr $COUNT1 \* \( $COUNT2 \* \( $COUNT3 + 1 \) + 1 \) + 1`

echo -n "Generating $exp_count entries: "

for lev1 in $seq1
do
	echo -n "."
	mkdir $lev1
	cd $lev1
	for lev2 in $seq2
	do
		mkdir $lev2
		( cd $lev2
			for lev3 in $seq3
			do
				echo $lev1-$lev2-$lev3 >> $lev3.txt
			done &
		)
	done
	cd ..
done

echo "!"
echo "Looking for them."

found=`$BINdflt st | wc -l`
if [[ $found -eq $exp_count ]]
then
  $SUCCESS "fsvs found all $exp_count changed entries."
else
  $ERROR_NB "fsvs found $found instead of $exp_count entries!"
	exit 1
fi


echo "Checkin ..."
$BIN ci -m many

echo "Checkout ..."
$WC2_UP_ST_COMPARE

