#!/usr/bin/perl

use Digest::MD5 qw(md5_hex);

$_=shift;

# Filename. If empty, just the path to the WAA is returned; if '^', the 
# path to the conf area is returned.
$file=shift; 

# The softroot - see the option "softroot".
( $softroot=shift ) =~ s,/+$,,;

# The WC base; defaults to the current directory.
$wc_base=shift() || $ENV{"PWD"} || die $!;

unless (m#^/#)
{
	$p=$ENV{"PWD"};
	$_ = $p . "/" . $_;
}

$conf = ($file =~ /^[A-Z]/);
$conf=1, $file="" if ($file eq '^');

1 while 
# remove /./ and /.
	s#/\./#/#g ||
	s#/\.$#/#g ||
# remove / at end; at least a single character (/) must be kept
	s#(.)/+$#\1#g ||
# change // to /
	s#//+#/#g;
# remove the softroot
die if $softroot && !s#^$softroot##;

die if $softroot && $wc_base !~ s#^$softroot##;
$wc_base =~ s# /+ $ # #gx;

#print "wc=$wc_base; entry=$_;\n";
$m=md5_hex($_);
if ($conf)
{
	print +($ENV{"FSVS_CONF"} || "/etc/fsvs"),
				"/" . $m . "/" . $file . "\n";
}
else
{
	$wc=substr(md5_hex($wc_base), 0, $ENV{"WAA_CHARS"}+0);
	print +($ENV{"FSVS_WAA"} || "/var/spool/fsvs"),
				"/" . $wc,
				"/" . substr($m,0,2),
				"/" . substr($m,2,2),
				"/" . substr($m,4),
				"/" . $file . "\n";
}

