#!/bin/bash

set -e 

anyfail=0
. ./test_functions

if [[ "$LC_ALL" != "" ]]
then
	$ERROR_NB "Using LC_ALL overrides the needed LC_MESSAGES setting."
	$ERROR "Please use LANG instead."
fi

for test in $TEST_LIST
do
	echo "" 
	tput setaf 4 || true 
	echo "_______________________________________________________" 
	echo "  \"$test\":1: ("`date`")"`tput op` 
	script=`pwd`/$test 
	if ! ( cd $TESTBASE && CURRENT_TEST=$test bash $BASH_VERBOSE $script 2>&1 )
	then
		echo "----++---- $script failed ----++----" 

		if [[ -z "$TEST_FAIL_WRITE_HDL" ]]
		then 
			exit 1 
		else
			if [[ "$anyfail" == 0 && -n "$TEST_TTY_HDL" ]]
			then 
				$ERROR_NB "First failed test is $test" > $TEST_TTY_HDL
			fi
			anyfail=1
			echo $test > $TEST_FAIL_WRITE_HDL
		fi
	fi
done

exit $anyfail

